### ISSUE TITLE
Pretty format console output

### ISSUE THREAD

**Issue by misbach** [suddi/claudia-local-api#12]
Thanks for building this project!

I'm having trouble reading the console output. Seems like it would be very helpful to pretty format the console output in a more human readable way... or maybe I'm using this wrong?

**Comment by suddi** [comment]
I am using [`bunyan`](https://www.npmjs.com/package/bunyan) to log the output to console.

So you can pipe the output to `bunyan` to pretty print it, eg.
````sh
claudia-local-api --api-module lib/app.js | bunyan --output short
````

You can see more examples of `bunyan` CLI usage [here](https://www.npmjs.com/package/bunyan#cli-usage)

**Comment by misbach** [comment]
@suddi Fantastic, yes this works. thanks for the tip!
