### ISSUE TITLE
Log error message as well as stack

### ISSUE THREAD

**Issue by jrbarnard** [suddi/claudia-local-api#27]
In logError we currently only log the stack, it would be good to log the message too, or just the entire error object:

```
function logError(logger, error) {
    // Probably better to log the entire thing as we may not have the message
    logger.error(error.message);
    logger.error(error.stack);
}
```
OR
```
function logError(logger, error) {
    logger.error(error);
}
```

What do you think?

**Comment by suddi** [comment]
Thanks for the report.

I have incorporated it into the latest release [3.0.4].
