### ISSUE TITLE
Minimist dependency is causing Moderate-level security issue when running npm audit

### ISSUE THREAD

**Issue by mjcella** [suddi/claudia-local-api#30]
The claudia-local-api package has minimist as one of its dependencies. Minimist recently had a security vulnerability reported with NPM. Running npm audit on a project with claudia-local-api installed returns the following:

| Moderate      | Prototype Pollution                     |
|---------------|-----------------------------------------|
| Package       | minimist                                |
| Patched in    | &gt;=0.2.1 &lt; 1.0.0  or &gt;=1.2.3                          |
| Dependency of | claudia-local-api                       |
| Path          | claudia-local-api > bunyan > mv > mkdirp > minimist            |
| More info     | https://nodesecurity.io/advisories/1179 |

**Comment by suddi** [comment]
Thanks for the report.

This has been corrected and should no longer be a problem anymore in the latest version [3.0.3].
