### ISSUE TITLE
Does this work with pathParams?

### ISSUE THREAD

**Issue by konsumer** [suddi/claudia-local-api#7]
If I have code like this, it works fine:

```js
import ApiBuilder from 'claudia-api-builder'

const api = new ApiBuilder()
module.exports = api

api.corsOrigin('*')

api.get('/search', (req) => {
  return 'works fine'
})
```

If I request `/search`, I get "works fine"

If I setup the function like this:

```js
api.get('/search/{term}', (req) => {
  return 'works fine:' + req.pathParams.term
})
```

and request `/search/cool`, I just get "{}", with a status 500.

**Comment by jacqui932** [comment]
+1 - Having the same problem

**Comment by misbach** [comment]
I can't seem to get query params to work either.

**Comment by suddi** [comment]
Yes, I have missed out this, will try to make some time to include this capability this week.

**Comment by suddi** [comment]
I have added handling for `pathParams` and published a new major version update of this library:
https://www.npmjs.com/package/claudia-local-api

Please see the example usage documented [here](https://github.com/suddi/claudia-local-api#usage).
Let me know if there are any problems getting this to work.

**Comment by suddi** [comment]
@misbach I had already developed the capability to handle query parameters in the previous version of this library.

Is there something I am missing?

**Comment by misbach** [comment]
@suddi Maybe I was doing something wrong. I've upgraded to your latest version and everything is working great. Thank you!
